### ISSUE TITLE
will this work on 5.5?

### ISSUE THREAD

**Issue by tyal** [vCheckReport/vCheck-vCD#14]
Hi community,
I have been looking for a reporting utility for my vcd 5.5 env.  I have used the vcheck reports in the past for vsphere...they are awesome!  Just wondering if this script works on vcd 5.5?  It looks like it hasn't been touched in a few years, curious if anyone has used it.  Thanks!

**Comment by smasterson** [comment]
Sure does

**Comment by tyal** [comment]
indeed it does, thanks!
